# Generated by Django 4.2.1 on 2023-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='New Post', max_length=100),
        ),
    ]
